### ISSUE TITLE
GeoDirectory Wrappers

### ISSUE THREAD

**Issue by stkclassi5** [Momizat/multinews#3]
A feature I would really like to see to complete our WP site beta.lifeinhoboken.com is GeoDirectory ( http://wpgeodirectory.com/ ) integration. At the moment, it looks like the body wrapper with MultiNews does not match the plugin's wrapper. This plugin could really be a great addition for MultiNews. 

Additional Reference:

Plugin Developer: 
" We have released few compatibility plugins that through hooks and filters modify plugin html wrappers to make them compatible with the theme html wrappers.

Examples are for enfold, genesis, x and avada: https://wordpress.org/plugins/tags/geodirectory / http://geodirectory.themetailors.com/tt/portfolio/avada-child-theme-for-gd/

You can either adopt one of these themes, or look into our plugin to see how the template html wrappers are adapted (normally about 10 lines of code are enough for an avarage theme)."

**Comment by Momizat** [comment]
https://wordpress.org/plugins/geodirectory-multinews-compatibility-pack/
